language: minimal

services:
  - docker

cache:
  directories:
    - .ci-cache

script:
  - >-
    DEBUG=1 ./ci
    POST_GENERATE='[[ ${?} -eq 0 ]] && git diff --exit-code'
    POST_FMT='[[ ${?} -eq 0 ]] && git diff --exit-code'
    GO_TEST_FLAGS='-race -coverprofile=coverage.txt'

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt -X fix
